// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9tXt9RHezd70iPIPHGKg_6RX913UzyIA',
    appId: '1:299645842881:web:705218b756842b6f3b6b40',
    messagingSenderId: '299645842881',
    projectId: 'rssi-attendance-system',
    authDomain: 'rssi-attendance-system.firebaseapp.com',
    storageBucket: 'rssi-attendance-system.firebasestorage.app',
    measurementId: 'G-Z18JXMZQ22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBeB1eI4dY-P1mDxOH6q7AE4qD1FO0BPE',
    appId: '1:299645842881:android:9f490c638563dae63b6b40',
    messagingSenderId: '299645842881',
    projectId: 'rssi-attendance-system',
    storageBucket: 'rssi-attendance-system.firebasestorage.app',
  );
}
